---
new_page_extension: md
auto_deploy: true
admin_path: "/admin"
webhook_url: 
sections: 
upload_dir: portfolio/.vuepress/public/upload
public_path: "/upload"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: portfolio/.vuepress/dist
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
